mfussenegger/nvim-dap-python

- README.md
- lua/dap-python.lua
This might require some extensions in nvim-dap as the source is set to
`<string>`. So currently if an exception raises and triggers a stopped
event it will fail because the cursor will be outside of the window.
> Add a method to debug the current selection

- lua/dap-python.lua
There may not be a non_ws in every line (if a line contains no characters). Error: comparing nil with a number.
> Fix bug in remove_indent (would not work for empty lines)

- lua/dap-python.lua
fixes default for empty host (`or` was progressing the empty string) and adds a default for the port (`5678` which seems to be the default preferred by `debugpy` in the docs)
> fix default for host and add default port

- lua/dap-python.lua
So that users only need to define the options they want to override.
> Extends opts with default opts

- README.md
- lua/dap-python.lua
Implements `test_class` and improves `test_method` to recognize that in
a construct as follows, `test_b` is not part of `class A`:
class A:
def test_a():
pass
def test_b():
pass
> Support test_class and handle class/function structure

- lua/dap-python.lua
Relates to
- https://github.com/mfussenegger/nvim-dap/issues/150
- https://github.com/mfussenegger/nvim-dap/commit/8b7e087af4e4772db84e47441492bd99a05c8664
> Remove `print('Running')` and add name to config

- lua/dap-python.lua
Only thing I'm not sure about is if [this line](https://github.com/mfussenegger/nvim-dap-python/blob/2e87b354a607a26f6706d04353e01c834ff36ee9/lua/dap-python.lua#L172) needs to be changed also. I'm not using unittest, and I'm not really sure exactly what's happening there, anyway...
> fix for venv python executable paths on Windows

- lua/dap-python.lua
So far you could only use the `Launch file` option if the current
working directory was on the same level as the file.
Changing the `program` path to absolute allows to debug files if you're
in the parent directy. E.g. if the source is in `src/main.py`.
> Set `program` to absolute path by default

- lua/dap-python.lua
Enable the ability to customize the pythonPath.
Useful for the case where debugpy & packages are installed in different envs.
> feat: add `pythonPath` to opts

- lua/dap-python.lua
Debugpy does not allow both settings at once so just added a check before adding `pythonPath`
> fix(enrich-config): check python arg

- README.md
- lua/dap-python.lua
To automatically detect the right runner users can do something like this:
```lua
local function mkopts()
if vim.loop.fs_stat('manage.py') then
return { test_runner = 'django' }
else
return { test_runner = 'unittest' }
end
end
local function test_method()
return dappy.test_method(mkopts())
end
local function test_class()
return dappy.test_class(mkopts())
end
local silent = { silent = true }
vim.keymap.set('n', '<leader>dn', test_method, silent)
vim.keymap.set('n', '<leader>df', test_class, silent)
```
(Might add something like this built-in if there's enough interest)
> Allow users to define their own test runners & add django runner

- lua/dap-python.lua
Just a small quality-of-life improvement. Without the change, if a user
calls `setup` like this
require('dap-python').setup(vim.fn.system('which python3'))
an error is thrown because the `system` call returns a value with a
trailing newline.
> fix: trim path to Python installation

- lua/dap-python.lua
Explicitly allow passing nil to the second parameter of the setup function as shown in the usage examples of this plugin. Otherwise, LSPs might report a missing parameter for this function.
> Allow SetupOpts to be nil in @param documentation

- lua/dap-python.lua
Until the `startDebugging` request is implemented in both nvim-dap and
debugpy it's safer to set it to false as it can cause issues with some
packages. See https://github.com/microsoft/debugpy/issues/1096
> Set `subProcess` to false if not present in config

- lua/dap-python.lua
With the upcoming debugpy and nvim-dap versions, debugging subprocesses
will be supported
> Don't set `subProcess` to false anymore if nil

- lua/dap-python.lua
Fixes deprecation warnings on nightly
> Prefer vim.treesitter.query.parse for nvim 0.9+

- lua/dap-python.lua
Hey,
When running windows, using "unittest", backwards slashes were not transformed to periods, rendering an invalid module path. My proposed solution [here](https://github.com/mfussenegger/nvim-dap-python/issues/91) contained a rather complex regex, so I decided to keep it simple and used the `is_windows` function.
Thanks for maintaining such a nice framework. I use it everyday!
Regards,
Bart
> bugfix: issue 91 -> Test runner "unittest" not working on windows

- lua/dap-python.lua
Fixes https://github.com/mfussenegger/nvim-dap-python/issues/110
> Ignore wildignore when expanding python path

- lua/dap-python.lua
`sysname` doesn't always contain `Windows`, depending on how Neovim is
run on Windows it can contain stuff like `MINGW32_NT-10.0`
Closes https://github.com/mfussenegger/nvim-dap-python/issues/115
> Make is-windows check more reliable

- lua/dap-python.lua
Extends the automatic python path detection by probing for some common
virtualenv locations.
Tries all - cwd/lcwd and lsp clients' root_dir as possible project
roots and uses the first that exists.
> Detect virtualenv by probing for venv, .venv, env and .env

- lua/dap-python.lua
Should solve https://github.com/mfussenegger/nvim-dap-python/issues/126
Maybe this is good enough - another option would be to double check the
if the python path exists, but that would add some extra workload.
> Only use venv, .venv, env or .env if it's a directory

- README.md
The readme didn't reflect the changes from https://github.com/mfussenegger/nvim-dap-python/pull/121
> Extend virtualenv section in README with folder detection info

- .gitignore
This is just so that when you generate the help tags with `:helptags`, the tags don´t make your index dirty.
> Add doc/tags to gitignore

- lua/dap-python.lua
> Fixes `default_runner` returning nil in some circumstances

- README.md
- doc/dap-python.txt
- lua/dap-python.lua
Changes `default_runner` to run its same logic over each folder path returned by `root_dirs()`, returning the first success - if none are found, it defaults to `unittest`.
Note: this removes the trailing `return 'unittest'` from within the `elseif uv.fs_stat("pyproject.toml") then ...` scope, and instead proceeds with checking the next root folder in the loop - this is intentional.
Also updates associated docs to note the logic.
> fix:default_runner: Look for marker files within all possible root_dirs

- lua/dap-python.lua
Should print "No test method found near cursor" instead of a stacktrace
if there is no function
> Fix missing method case handling in test_method

- README.md
I wasn't fully aware of how the plugin worked so I assumed that the example in the README would setup python3 for me, as nobody uses python2 anymore (well, at least almost nobody :/).
> README.md: Use python3 in the setup example

- lua/dap-python.lua
Based on https://github.com/microsoft/debugpy/pull/1404 the event is
informative. It shouldn't result in warning logs if the information
isn't used.
> Mute debugpySockets event warning log messages

- lua/dap-python.lua
The shorter names work better using `:DapNew` with arguments
> Shorten names of debug configs

- lua/dap-python.lua
It treats quoted strings as one argument
> Use dap.utils splitstr if available for file:args config
